apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-pipeline-gateway
spec:
  selector:
    matchLabels:
      app: mini-pipeline-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: mini-pipeline-gateway
    spec:
      containers:
        - name: mini-pipeline-gateway
          image: idock.daumkakao.io/moon_dev/model_prediction_mini_pipeline
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: mini-pipeline-gateway-svc
spec:
  selector:
    app: mini-pipeline-gateway
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mini-pipeline-gateway-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: moon.dev.daumkakao.io
      http:
        paths:
          - path: /
            backend:
              serviceName: mini-pipeline-gateway-svc
              servicePort: 8080