apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-pipeline-gateway
spec:
  selector:
    matchLabels:
      app: mini-pipeline-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: mini-pipeline-gateway
    spec:
      containers:
        - name: mini-pipeline-gateway
          image: idock.daumkakao.io/moon_dev/model_prediction_mini_pipeline:gw_latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >
                –Dspring.profiles.active=dev
                -javaagent:/share-vol/apm/apm.agent.jar
                -Dapm_application_key=b3928f93708449e5b497d88d5971af7d
                -Dapm_collector_address=apm-collector.onkakao.net
                -Dsentry.dsn=https://b3928f93708449e5b497d88d5971af7d@aem-ingest.onkakao.net/18647
          volumeMounts:
            - name: share-vol
              mountPath: /share-vol
      initContainers:
        - name: apm-initializer
          image: idock.daumkakao.io/kakaoapm/apm-pod-init:1.5
          imagePullPolicy: Always
          env:
            - name: APM_VOLUME_DIR
              value: /share-vol/apm
          volumeMounts:
            - name: share-vol
              mountPath: /share-vol
      volumes:
        - name: share-vol
          emptyDir: {}
---

apiVersion: v1
kind: Service
metadata:
  name: mini-pipeline-gateway-svc
spec:
  selector:
    app: mini-pipeline-gateway
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80