apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-pipeline-model-server
spec:
  selector:
    matchLabels:
      app: mini-pipeline-model-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mini-pipeline-model-server
    spec:
      containers:
        - name: mini-pipeline-model-server
          image: idock.daumkakao.io/moon_dev/model_prediction_mini_pipeline:ms_latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: mini-pipeline-ms-svc
spec:
  selector:
    app: mini-pipeline-model-server
  ports:
    - protocol: TCP
      targetPort: 8000
      port: 80